
const char C_MKSEGEMNT[C_MKSEGEMNT_COUNT][MAXAGG_LEN + 1] = {
    "AUTOMOBILE",
    "BUILDING",
    "FURNITURE",
    "HOUSEHOLD",
    "MACHINERY",
};

// COUNT:92
const char P_NAME_COLOR[P_NAME_COLOR_COUNT][COLOR_LEN + 1] = {
    "almond",
    "antique",
    "aquamarine",
    "azure",
    "beige",
    "bisque",
    "black",
    "blanched",
    "blue",
    "blush",
    "brown",
    "burlywood",
    "burnished",
    "chartreuse",
    "chiffon",
    "chocolate",
    "coral",
    "cornflower",
    "cornsilk",
    "cream",
    "cyan",
    "dark",
    "deep",
    "dim",
    "dodger",
    "drab",
    "firebrick",
    "floral",
    "forest",
    "frosted",
    "gainsboro",
    "ghost",
    "goldenrod",
    "green",
    "grey",
    "honeydew",
    "hot",
    "indian",
    "ivory",
    "khaki",
    "lace",
    "lavender",
    "lawn",
    "lemon",
    "light",
    "lime",
    "linen",
    "magenta",
    "maroon",
    "medium",
    "metallic",
    "midnight",
    "mint",
    "misty",
    "moccasin",
    "navajo",
    "navy",
    "olive",
    "orange",
    "orchid",
    "pale",
    "papaya",
    "peach",
    "peru",
    "pink",
    "plum",
    "powder",
    "puff",
    "purple",
    "red",
    "rose",
    "rosy",
    "royal",
    "saddle",
    "salmon",
    "sandy",
    "seashell",
    "sienna",
    "sky",
    "slate",
    "smoke",
    "snow",
    "spring",
    "steel",
    "tan",
    "thistle",
    "tomato",
    "turquoise",
    "violet",
    "wheat",
    "white",
    "yellow",
    };

// COUNT : 150
const char P_TYPE[P_TYPE_COUNT][P_TYPE_LEN + 1] = {
    "STANDARD ANODIZED TIN",
    "STANDARD ANODIZED NICKEL",
    "STANDARD ANODIZED BRASS",
    "STANDARD ANODIZED STEEL",
    "STANDARD ANODIZED COPPER",
    "STANDARD BURNISHED TIN",
    "STANDARD BURNISHED NICKEL",
    "STANDARD BURNISHED BRASS",
    "STANDARD BURNISHED STEEL",
    "STANDARD BURNISHED COPPER",
    "STANDARD PLATED TIN",
    "STANDARD PLATED NICKEL",
    "STANDARD PLATED BRASS",
    "STANDARD PLATED STEEL",
    "STANDARD PLATED COPPER",
    "STANDARD POLISHED TIN",
    "STANDARD POLISHED NICKEL",
    "STANDARD POLISHED BRASS",
    "STANDARD POLISHED STEEL",
    "STANDARD POLISHED COPPER",
    "STANDARD BRUSHED TIN",
    "STANDARD BRUSHED NICKEL",
    "STANDARD BRUSHED BRASS",
    "STANDARD BRUSHED STEEL",
    "STANDARD BRUSHED COPPER",
    "SMALL ANODIZED TIN",
    "SMALL ANODIZED NICKEL",
    "SMALL ANODIZED BRASS",
    "SMALL ANODIZED STEEL",
    "SMALL ANODIZED COPPER",
    "SMALL BURNISHED TIN",
    "SMALL BURNISHED NICKEL",
    "SMALL BURNISHED BRASS",
    "SMALL BURNISHED STEEL",
    "SMALL BURNISHED COPPER",
    "SMALL PLATED TIN",
    "SMALL PLATED NICKEL",
    "SMALL PLATED BRASS",
    "SMALL PLATED STEEL",
    "SMALL PLATED COPPER",
    "SMALL POLISHED TIN",
    "SMALL POLISHED NICKEL",
    "SMALL POLISHED BRASS",
    "SMALL POLISHED STEEL",
    "SMALL POLISHED COPPER",
    "SMALL BRUSHED TIN",
    "SMALL BRUSHED NICKEL",
    "SMALL BRUSHED BRASS",
    "SMALL BRUSHED STEEL",
    "SMALL BRUSHED COPPER",
    "MEDIUM ANODIZED TIN",
    "MEDIUM ANODIZED NICKEL",
    "MEDIUM ANODIZED BRASS",
    "MEDIUM ANODIZED STEEL",
    "MEDIUM ANODIZED COPPER",
    "MEDIUM BURNISHED TIN",
    "MEDIUM BURNISHED NICKEL",
    "MEDIUM BURNISHED BRASS",
    "MEDIUM BURNISHED STEEL",
    "MEDIUM BURNISHED COPPER",
    "MEDIUM PLATED TIN",
    "MEDIUM PLATED NICKEL",
    "MEDIUM PLATED BRASS",
    "MEDIUM PLATED STEEL",
    "MEDIUM PLATED COPPER",
    "MEDIUM POLISHED TIN",
    "MEDIUM POLISHED NICKEL",
    "MEDIUM POLISHED BRASS",
    "MEDIUM POLISHED STEEL",
    "MEDIUM POLISHED COPPER",
    "MEDIUM BRUSHED TIN",
    "MEDIUM BRUSHED NICKEL",
    "MEDIUM BRUSHED BRASS",
    "MEDIUM BRUSHED STEEL",
    "MEDIUM BRUSHED COPPER",
    "LARGE ANODIZED TIN",
    "LARGE ANODIZED NICKEL",
    "LARGE ANODIZED BRASS",
    "LARGE ANODIZED STEEL",
    "LARGE ANODIZED COPPER",
    "LARGE BURNISHED TIN",
    "LARGE BURNISHED NICKEL",
    "LARGE BURNISHED BRASS",
    "LARGE BURNISHED STEEL",
    "LARGE BURNISHED COPPER",
    "LARGE PLATED TIN",
    "LARGE PLATED NICKEL",
    "LARGE PLATED BRASS",
    "LARGE PLATED STEEL",
    "LARGE PLATED COPPER",
    "LARGE POLISHED TIN",
    "LARGE POLISHED NICKEL",
    "LARGE POLISHED BRASS",
    "LARGE POLISHED STEEL",
    "LARGE POLISHED COPPER",
    "LARGE BRUSHED TIN",
    "LARGE BRUSHED NICKEL",
    "LARGE BRUSHED BRASS",
    "LARGE BRUSHED STEEL",
    "LARGE BRUSHED COPPER",
    "ECONOMY ANODIZED TIN",
    "ECONOMY ANODIZED NICKEL",
    "ECONOMY ANODIZED BRASS",
    "ECONOMY ANODIZED STEEL",
    "ECONOMY ANODIZED COPPER",
    "ECONOMY BURNISHED TIN",
    "ECONOMY BURNISHED NICKEL",
    "ECONOMY BURNISHED BRASS",
    "ECONOMY BURNISHED STEEL",
    "ECONOMY BURNISHED COPPER",
    "ECONOMY PLATED TIN",
    "ECONOMY PLATED NICKEL",
    "ECONOMY PLATED BRASS",
    "ECONOMY PLATED STEEL",
    "ECONOMY PLATED COPPER",
    "ECONOMY POLISHED TIN",
    "ECONOMY POLISHED NICKEL",
    "ECONOMY POLISHED BRASS",
    "ECONOMY POLISHED STEEL",
    "ECONOMY POLISHED COPPER",
    "ECONOMY BRUSHED TIN",
    "ECONOMY BRUSHED NICKEL",
    "ECONOMY BRUSHED BRASS",
    "ECONOMY BRUSHED STEEL",
    "ECONOMY BRUSHED COPPER",
    "PROMO ANODIZED TIN",
    "PROMO ANODIZED NICKEL",
    "PROMO ANODIZED BRASS",
    "PROMO ANODIZED STEEL",
    "PROMO ANODIZED COPPER",
    "PROMO BURNISHED TIN",
    "PROMO BURNISHED NICKEL",
    "PROMO BURNISHED BRASS",
    "PROMO BURNISHED STEEL",
    "PROMO BURNISHED COPPER",
    "PROMO PLATED TIN",
    "PROMO PLATED NICKEL",
    "PROMO PLATED BRASS",
    "PROMO PLATED STEEL",
    "PROMO PLATED COPPER",
    "PROMO POLISHED TIN",
    "PROMO POLISHED NICKEL",
    "PROMO POLISHED BRASS",
    "PROMO POLISHED STEEL",
    "PROMO POLISHED COPPER",
    "PROMO BRUSHED TIN",
    "PROMO BRUSHED NICKEL",
    "PROMO BRUSHED BRASS",
    "PROMO BRUSHED STEEL",
    "PROMO BRUSHED COPPER",
};

const char P_CONTAINER[P_CONTAINER_COUNT][P_CNTR_LEN + 1] = {
    "SM CASE",
    "SM BOX",
    "SM BAG",
    "SM JAR",
    "SM PACK",
    "SM PKG",
    "SM CAN",
    "SM DRUM",
    "LG CASE",
    "LG BOX",
    "LG BAG",
    "LG JAR",
    "LG PACK",
    "LG PKG",
    "LG CAN",
    "LG DRUM",
    "MED CASE",
    "MED BOX",
    "MED BAG",
    "MED JAR",
    "MED PACK",
    "MED PKG",
    "MED CAN",
    "MED DRUM",
    "JUMBO CASE",
    "JUMBO BOX",
    "JUMBO BAG",
    "JUMBO JAR",
    "JUMBO PACK",
    "JUMBO PKG",
    "JUMBO CAN",
    "JUMBO DRUM",
    "WRAP CASE",
    "WRAP BOX",
    "WRAP BAG",
    "WRAP JAR",
    "WRAP PACK",
    "WRAP PKG",
    "WRAP CAN",
    "WRAP DRUM",
};

const char L_RETURNFLAG[L_RETURNFLAG_COUNT][2] = {
    "R","A",
};

const char L_SHIPINSTRUCT[L_SHIPINSTRUCT_COUNT][MAXAGG_LEN + 1] = {
    "DELIVER IN PERSON",
    "COLLECT COD",
    "TAKE BACK RETURN",
    "NONE",
};

const char L_SHIPMODE[L_SHIPMODE_COUNT][MAXAGG_LEN + 1] = {
    "REG AIR",
    "AIR",
    "RAIL",
    "TRUCK",
    "MAIL",
    "FOB",
    "SHIP",
};

// COUNT: 5
const char O_ORDERPRIORITY[O_ORDERPRIORITY_COUNT][MAXAGG_LEN + 1] = {
    "1-URGENT",
    "2-HIGH",
    "3-MEDIUM",
    "4-NOT SPECIFIED",
    "5-LOW",
};
